import org.apache.hadoop.fs.shell.PathExceptions.PathIOException;
public class FunctionUse9732 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
}
}