import org.apache.hadoop.fs.shell.PathExceptions.PathIOException;
public class FunctionUse9726 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
pathioexception.getPath();
}
}